### ISSUE TITLE
Monotonic counter decreases when builds expire

### ISSUE THREAD

**Issue by ghebu** [jenkinsci/prometheus-plugin#539] opened 2023-07-18 16:56 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

AmazonLinux2

### Reproduction steps

Create a build and run it a few times with both successes and failures
Configure Jenkins to expire/discard old builds
Observe that metrics that are counters go down (successful and failed builds for example)

### Expected Results

Counter. A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart.

### Actual Results

The counters go down, which causes alerts based on these values to fire.

### Anything else?

Reference to closed (but unresolved) issue: https://github.com/jenkinsci/prometheus-plugin/issues/327

Prometheus plugin version: 2.1.2
Jenkins version: 2.375.4

**Comment by Waschndolos** [comment] 2023-07-21 15:47
Thank's for the report. If that's the case that they go down that's clearly an error as you say, counter should only increase. I'll check if I can reproduce the error in the master branch after my refactoring. Could have been resolved through that. I'll check.

**Comment by Waschndolos** [comment] 2023-08-26 14:36
Ok I think I found it. The counter for builds_success_build_count_total for example is calculated for each job. It get's all builds of the job and increses the counter for the job. So it only has those builds available which it gets from the job object. If you have configured the Job to discard old builds it calculates it based on builds available and not all builds which are ever built. So in this case the metric cannot be a counter it's a gauge.

**Comment by ghebu** [comment] 2023-08-28 10:59
Thank you @Waschndolos for your effort! The issue can be closed. 

My goal was to have a per day aggregation so I've done that with some plain groovy. A single job that does the query on the pipelines, retrieve the build time and then push it as a metric in Prometheus. 

Have a good one!

**Comment by adriengardou** [comment] 2023-08-30 12:39
hi @ghebu, I ran into the same issue and updating those counters seems rather complex. I would be interested to take a peek at your groovy code if you don't mind ?

**Comment by yogeek** [comment] 2023-10-12 15:41
I also tried to get the number of successful pipelines during the last 24h in prometheus with the `jenkins_builds_success_build_count_total` and was surprise to see it decreased when a job was cleaned up.

@Waschndolos said it should be a jauge and not a counter
But I just installed this plugin in its latest version and the metric type is still "counter"
So do not understand why this issue is closed...

Can you help me understand please ?

**Comment by Waschndolos** [comment] 2023-10-12 16:29
@yogeek Indeed. I don't know why I closed it. I must have been in a hurry or so  - I'll reopen it and change the types

**Comment by yogeek** [comment] 2023-10-12 16:44
Thanks @Waschndolos !

And is there a way to have a "real" counter in order to achieve what we wanted initially (i.e. get a count of all successful pipelines in the last 24h, even if some pipeline have been deleted because of the cleanup rule) with this plugin ?

**Comment by adriengardou** [comment] 2023-10-12 16:51
I'm on my way to propose a PR for getting real counters when I'll get some
time to refine my modifications. Might need some help to meet contribution
requirements.

Le jeu. 12 oct. 2023, 18:45, Guillaume Dupin ***@***.***> a
écrit :

**Comment by Waschndolos** [comment] 2023-10-12 16:56
@adriengardou. That's some good news thank you. Happy to help then. But keep in mind, the Plugin iterates every X Seconds over the Jenkins Status. It only sees what jenkins has as Jobs/Build at that given time. Let's say you have this:

Build1 - FAILED
Buidl2 - FAILED
Build3 - SUCCESS

so the Failure count would be 2. Now you configured your pipeline to only keep 3 Builds with the BuildDiscarder Plugin for instance.  On the next run you'll have this:

Build2 - FAILED
Build3 - SUCCESS
Build4 - SUCCESS

In that iteration the Prometheus plugins only gets these 3 builds from the Job object so the Failure count would be 1. So for me it's more like a Gauge as I don't have the history of the Builds available - But curious on your PR, maybe I'm wrong here

**Comment by adriengardou** [comment] 2023-10-12 17:02
You're right, this PR will rewrite counters observation mechanism and keep
data in memory (don't support restarts though) and add some deprecated data
discarder.

I can anyway submit a draft real soon to start some design discussions.
Just need to assert my updates are valid in production mode.

Le jeu. 12 oct. 2023, 18:57, Waschndolos ***@***.***> a
écrit :

**Comment by yogeek** [comment] 2023-10-12 18:19
Thanks for working on this @adriengardou 👍

Now that @Waschndolos explained how the plugin works, indeed we need a way to store a state to avoid loosing information when builds disappear.

I wondered if storing this state will not be possible using a Prometheus record rule, based on the raw metric...
This would allow to store the state in Prometheus itself, to not loose this state upon restart and to simplify Prometheus requests to have a 'real' counter (i.e. that always increases)

I am not a Prometheus expert so I do not know if such a record is possible to write (what would be the computed request that would allow store the state over the time) but I am curious about your opinion about this.

**Comment by adriengardou** [comment] 2023-10-13 12:35
Unfortunately that wouldn't be reliable as prometheus is based on a polling
system to fetch metrics. You can sure work woth gauges and aggregate on
prometheus, that would also means that you can miss some values from
jenkins if there is any interruption in monitoring service.
Only storing metric on jenkins would be reliable enough IMO.

Le jeu. 12 oct. 2023, 20:19, Guillaume Dupin ***@***.***> a
écrit :

**Comment by yogeek** [comment] 2023-10-13 13:11
Ok I see.

And usually a counter is based on an event to increase each time an event is happening.
Is it possible for a Jenkins plugin to watch Jenkins event to detect the successful ending of a pipeline (and increasing the counter) instead of getting the number of successful builds?

**Comment by adriengardou** [comment] 2023-10-24 13:15
I opened a PR as draft to start discussions. Still need to be rebased on newer commits and follow contribution rules.

**Comment by aidanleuck** [comment] 2023-12-17 23:15
I don't think this PR will achieve correct counter metrics when the Jenkins instance restarts. The way counter metrics are calculated in Prometheus on a counter restart is the count before restart + count after restart. Once the instance restarts we will forget the last build that we read since it only exists and memory and the counter will be set back to 8. So we are still effectively double-counting some builds. I am working on a PR based on the latest release that will address these issues by incrementing the counter when a job is completed.

**Comment by adriengardou** [comment] 2023-12-18 08:56
hi @aidanleuck and thank you for providing additionnal hands of that topic !

So yes, like I previously mentioned, my PR doesn't support restarts.  It would need to save current cache map state on filesystem (or anything alike).
I'm not sure about what you mean by 
> The way counter metrics are calculated in Prometheus on a counter restart is the count before restart + count after restart. 

but prometheus is not aggregating any counter value, just reporting exposed ones. So in my PR, and after a restart, you will only loose metrics about discarded builds (and have a decrease) but not double counting some ?
Having a hook on a finishing job would be great indeed, how do you plan to avoid decreases on restart ?

**Comment by aidanleuck** [comment] 2023-12-18 15:58
hi @adriengardou watching this YouTube video will explain a lot as far as how counter resets work. Prometheus does a lot of the heavy lifting for you so you don't have to worry about avoiding decreases on restart and saving state. If you start watching at 3 minutes he explains how increase/rate functions are calculated when a counter is reset. (A reset is assumed whenever the counter decreases in value)
https://www.youtube.com/watch?v=7uy_yovtyqw. 

The idea is to basically not save the state of the counter at all and just let it reset to zero upon restart. Prometheus will automatically account for the reset on the next scrape since the counter decreased. If I understand your PR correctly, it tries to get around the issue by caching old jobs that have been discarded so the counter is always up to date. This works fine, assuming the instance doesn't restart and the counter continuously increases. Since the existing implementation and your PR looks at job history to determine the counter value, I believe it could cause some unwanted side effects.

Example: You have a job that ran 15 builds but had discarded 5 of them, the counter before the instance is reset will show the correct counter value 15 since your PR adds the job cache. Upon restart though the cache will get wiped and we will scrape the job again. This will update the counter to 10 since we are no longer accounting for the discarded builds. Since Prometheus saw the value drop from 15 to 10 it will assume there was a counter reset, when it performs an increase calculation it will adjust for the reset, but instead of Prometheus calculating 15 on a reset to zero it will calculate 15 + 10 since 15 was lower than the previous counter value. I hope this explanation is helpful, but if you need any more clarification I would be happy to do so.

**Closed** 2023-12-29 04:57 UTC
Labels: bug

**Comment by adriengardou** [comment] 2024-01-16 09:57
hi @aidanleuck, you're right  about my PR having flaws over a Jenkins restart. And your code about iterating jobs is better when it is assumed to have reset on restarts indeed.

Also thank you about improving tests in your PR, that will help in the future.

I must say that I know about increase/rate functions, but be aware of interpolation made by prometheus (cf https://www.youtube.com/watch?v=67Ulrq6DxwA). In my case I need to stick to precise values so I can't use those ones (irate is an still option).
So I'm still trying to get a saved state over restart to avoid getting decreases. Let's say if you have a temporary flaky Jenkins instance, it will mess with your metrics and I think we can have a more robust method IMO. A persistent storage will solve that.

Let me know if you're still interested in that solution of mine and I'll reopen and update in the future.

**Comment by aidanleuck** [comment] 2024-01-16 15:34
Hi @adriengardou, yes there is the possibility that you can lose data if your instance is restarted often, but I believe we are only missing a two minute window between each scrape. For me that standard of error is acceptable, but I understand if you need 100% accurate data. I am aware of interpolation caused by Prometheus as well and it caused me some headache when trying to get stats as opposed to graphs. These are what I have done that seem to work well for me.

1) When performing the query use an instant calculation instead of a range calculation. When using range functions I have been able to accurately calculate data using instant calculation since it sums up all of the data over a window into a single point at the instant the data was requested. This has allowed me to get consistent data over the time period and seems to mitigate interpolation... but I could be wrong there. 

2) Use VictoriaMetrics as your backend. VictoriaMetrics is a Prometheus compatible backend that has pure functions for calculating ranges. (It doesn't interpolate over the window)

If none of these solutions are viable a PR is always welcome, just wanted to see if I could save you some time by looking at the other two options I listed above.
