### ISSUE TITLE
Prometheus plugin endpoint showing blank page

### ISSUE THREAD

**Issue by mohanss08** [jenkinsci/prometheus-plugin#208] opened 2021-02-19 04:08 UTC
Below is my jenkins environment.

```
Jenkins - 2.263.1(LTS) deployed through tomcat.
Prometheus metrics plugin - 2.0.8 
```

`http://jenkins-server/jenkins/prometheus` just shows the blank page on my browsers.

My prometheus.yml

```
  - job_name: 'jenkins'
    metrics_path: '/jenkins/prometheus'
    scheme: http
    static_configs:
    - targets: ['jenkins-server:80']
```
Even tried with authentication, however still blank page shown.

```
basic_auth:
  username: domain-user
  password: 98qw37asdkdsjfeiq1dedsewe
```

Jenkins `system log` section below message shown.

```
A thread (prometheus_async_worker thread/77119) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NullPointerException
```
Refered this issue - `https://github.com/jenkinsci/prometheus-plugin/issues/82` however it is closed, can't find the workaround in that.

**Comment by daniadias** [comment] 2021-02-19 17:40
I have the same problem :(

**Comment by boostrack** [comment] 2021-02-26 15:32
try restarting jenkins after installing plugin. I had this behaviour when i **uninstalled** plugin due to OOM issues \\did not restart jenkins.

**Comment by mohanss08** [comment] 2021-02-26 15:39
I did that few times, however still experiencing the same issue.

**Comment by fasatrix** [comment] 2021-03-05 06:35
Have the same issue.. we run our Jenkins master on aws ecs and all new versions of plugins are installed via casc overnight with latest Jenkins lts (we basically "restart"  it daily). Any ETA to resolve this?

**Comment by jsmilani** [comment] 2021-03-16 18:34
There are a handful of similar tickets and I believe some root causes have been resolved and merged but we are waiting for the next release. Any updates on when this will be released? A lot of us are waiting and unable to use the plugin due to the bugs.

**Comment by fasatrix** [comment] 2021-03-16 20:52
> Any updates on when this will be released? A lot of us are w

this plugin should be be put for adoption as no very reactive response

**Comment by oleg-nenashev** [comment] 2021-03-21 08:34
CC @markyjackson-taulia regarding the plugin adoption ^

**Comment by msven** [comment] 2021-03-21 11:56
@oleg-nenashev @fasatrix 

https://github.com/jenkinsci/prometheus-plugin/discussions/203

**Comment by markyjackson-taulia** [comment] 2021-03-21 12:58
I will be doing a release today that will fix this.
Thank you for pinging me @oleg-nenashev

**Comment by markyjackson-taulia** [comment] 2021-03-21 14:42
Please update to the latest version. See issue #231

**Closed by markyjackson-taulia** 2021-03-21 14:42 UTC
